export function BoardCertifications() {
  return (
    <>
      <img
        src='/images/instinct/one.png'
        alt=''
        aria-hidden
        className='
          pointer-events-none
          absolute
          right-[8%]
          top-[6%]
          w-40
          rotate-[10deg]
          opacity-75
        '
      />

      <img
        src='/images/instinct/two.png'
        alt=''
        aria-hidden
        className='
          pointer-events-none
          absolute
          left-[42%]
          top-[20%]
          w-36
          -rotate-[8deg]
          opacity-70
        '
      />

      <img
        src='/images/instinct/three.png'
        alt=''
        aria-hidden
        className='
          pointer-events-none
          absolute
          left-[55%]
          bottom-[28%]
          w-40
          rotate-[6deg]
          opacity-70
        '
      />

      <img
        src='/images/instinct/four.png'
        alt=''
        aria-hidden
        className='
          pointer-events-none
          absolute
          left-[12%]
          bottom-[18%]
          w-36
          -rotate-[5deg]
          opacity-70
        '
      />
    </>
  );
}
