export const casingAssets = {
  cover: "/images/world/casing/atlas-cover.png",
  card: "/images/world/casing/card.png",
  cardBright: "/images/world/casing/card-bright.png",
};

export const dividerAssets = {
  small: "/images/world/elements/world-dividers/small-divider.PNG",
  vintage: "/images/world/elements/world-dividers/vintage-divider.PNG",
  berries: "/images/world/elements/world-dividers/berries.PNG",
  fish: "/images/world/elements/world-dividers/fish.PNG",
  redBerries: "/images/world/elements/world-dividers/red-berries.PNG",
  redRoundBerries: "/images/world/elements/world-dividers/red-round-berries.PNG",
};

export const stampAssets = {
  guide: "/images/world/elements/new-logo.png",
  sun: "/images/world/elements/world-stamps/sun.PNG",
  label: "/images/world/elements/world-stamps/sticket.PNG",
  mountainRoad: "/images/world/elements/world-stamps/mountains-road.PNG",
  squareLeafs: "/images/world/elements/world-stamps/square-leafs.PNG",
  paw: "/images/world/elements/world-stamps/paw.PNG",
  pawPop: "/images/world/elements/world-stamps/paw-pop.PNG",
  seeds: "/images/world/elements/world-stamps/seeds.PNG",
  fourSeeds: "/images/world/elements/world-stamps/4-seeds.PNG",
  berryLeafes: "/images/world/elements/world-stamps/berry-leafes.PNG",
  cocoaSeed: "/images/world/elements/world-stamps/cocoa-seed.PNG",
  flower: "/images/world/elements/world-stamps/flower.PNG",
  doubleFlower: "/images/world/elements/world-stamps/double-flower.PNG",
  leafBurnt: "/images/world/elements/world-stamps/leaf-burnt.PNG",
  leafCurved: "/images/world/elements/world-stamps/leaf-curved.PNG",
  leafRight: "/images/world/elements/world-stamps/leaf-right.PNG",
  leafRound: "/images/world/elements/world-stamps/leaf-round.PNG",
};

export const seedLeafSpecimens = [
  ["berries", "Berries", "garden finding"],
  ["brown-string", "Brown vine", "forest cord"],
  ["burnt-cup-flower", "Cup flower", "dry meadow"],
  ["burnt-flower", "Burnt flower", "sun field"],
  ["burnt-flower1", "Field flower", "trail bloom"],
  ["burnt-mushroom", "Brown mushroom", "forest shade"],
  ["burnt-mushroom2", "Round mushroom", "fallen log"],
  ["burnt-mushroom3", "Cap mushroom", "damp soil"],
  ["burnt-seed-opened-back", "Opened seed", "pod study"],
  ["burnt-seed-opened", "Split seed", "seed case"],
  ["burnt-seed", "Wild seed", "pantry find"],
  ["burnt-spike-bloomed", "Bloomed spike", "field grass"],
  ["burnt-spike-upside-down", "Dry spike", "grass marker"],
  ["burnt-spike", "Trail spike", "edge growth"],
  ["green-double-mushroom", "Green mushroom", "moss bed"],
  ["green-leaf-lefft", "Left leaf", "botanical note"],
  ["green-leaf-right", "Right leaf", "botanical note"],
  ["green-leaf-round-left", "Round leaf", "garden record"],
  ["green-leaf-round-spread", "Leaf spread", "soft greens"],
  ["green-mushroom", "Green cap", "forest floor"],
  ["green-mushroom3", "Tall mushroom", "damp trail"],
  ["green-small-leafs", "Small leaves", "herb cluster"],
  ["green-spike-bloomed", "Green spike", "field edge"],
  ["green-string", "Green vine", "trail cord"],
  ["green-wide-leafs", "Wide leaves", "garden greens"],
  ["more-berries", "More berries", "bright harvest"],
  ["oyster-mushroom", "Oyster mushroom", "bark shelf"],
  ["oyster-mushroom1", "Shelf mushroom", "woodland note"],
  ["purple-sunflower", "Purple flower", "meadow marker"],
  ["purple-sunflower1", "Violet bloom", "flower press"],
  ["seed-opened-front", "Open seed", "front study"],
  ["tree-root-small", "Small root", "soil record"],
  ["tree-root-spread", "Root spread", "deep earth"],
  ["tree-root", "Tree root", "forest anchor"],
  ["yellow-double-mushroom", "Yellow mushroom", "warm shade"],
  ["yellow-flower-marker", "Yellow marker", "field tag"],
  ["yellow-mushroom", "Yellow cap", "moss record"],
  ["yellow-sunflower", "Sun flower", "sun patch"],
  ["yellow-sunflower1", "Gold bloom", "pressed find"],
] as const;

export const specimenSrc = (name: string) =>
  `/images/world/elements/world-seeds-leafs/${name}.PNG`;
